# Generated by Django 3.1.3 on 2023-01-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('postdate', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('hobby', '趣味'), ('study', '勉強'), ('other', 'その他')], max_length=30)),
            ],
        ),
    ]
